# Generated by Django 2.0.1 on 2018-03-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShowGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Genre')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Show')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_nr',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='episode',
            name='season_nr',
            field=models.IntegerField(default=None),
        ),
    ]
