# Generated by Django 2.0.1 on 2018-03-11 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20180311_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Episode')),
            ],
        ),
        migrations.RemoveField(
            model_name='show',
            name='genre',
        ),
    ]
