# Generated by Django 2.0.1 on 2018-03-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_auto_20180311_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release',
            field=models.CharField(max_length=4),
        ),
    ]
