# Generated by Django 2.0.1 on 2018-03-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_auto_20180312_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='season_nr',
            field=models.IntegerField(),
        ),
    ]
