# Generated by Django 2.0.1 on 2018-03-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_auto_20180312_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='season_nr',
            field=models.IntegerField(default=None),
        ),
    ]
